services:

  laravel-docker:
    container_name: laravelapp
    build: .
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 9000:80
    user: "www-data:www-data"
  
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: autoconf_veiculos
    ports:
    - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
